# 项目名称、版本、版权年份
cendev:
  #名称
  name: 北京市电子政务内网大数据平台
  #版本
  version: 3.1.0
  #描述
  description: 北京市电子政务内网大数据平台
  #年份
  copyrightYear: 2018
  #头像上传路径
  profile: D:/cendev/file
#开发环境配置
server:
  #端口
  port: 8055
  tomcat:
    uri-encoding: utf-8
#日志配置
logging:
  level:
    com.censoft: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
#Spring配置
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
  messages:
    #国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: project,druiddev
#    active: project,druid,nw
#    active: project,druid,nw,ww
  #文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB


  devtools:
    restart:
      #禁用devtools模块的热部署功能
      enabled: true
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.censoft.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEbabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

  filterChainAnonMap:
    # 对静态资源设置匿名访问
    - '/favicon.ico**'
    - '/mainlogo.png**'
    - '/css/**'
    - '/docs/**'
    - '/fonts/**'
    - '/img/**'
    - '/ajax/**'
    - '/js/**'
    - '/file/**'
    - '/cendev/**'
    - '/druid/**'
    - '/captcha/captchaImage**'
  filterChainLogoutMap:
    # 退出 logout地址，shiro去清除session
    - '/logout'
  filterChainValidateMap:
    # 不需要拦截的访问
    - '/login'
    - '/action/taskManager/load-crawled-data.jsp'
    - '/action/taskManager/save-task.jsp'
    - '/action/taskManager/load-task-by-user.jsp'
    - '/action/taskManager/save-task-group.jsp'
    - '/action/taskManager/dele-task.jsp'
    - '/action/taskManager/dele-task-group.jsp'
    - '/action/taskManager/create-new-table.jsp'
    - '/action/taskManager/update-task-flownodes.jsp'
    - '/action/taskManager/keep-session.jsp'
    - '/action/config/load.jsp'
    - '/action/config/save.jsp'
    - '/action/config/load-flow-designer.jsp'
    - '/action/config/update-flow-designer.jsp'
    - '/action/config/copy-app.jsp'
    - '/action/taskManager/load-page-data.jsp'
    - '/action/app/synchro/list'
    - '/action/app/synchro/change'
    - '/action/app/synchro/changecjs'
    - 'action/app/synchro/table'
    - 'action/app/synchro/time'
    - '/action/taskManager/load-crawled-data-count.jsp'
    - '/notice/getInfo'
    - '/module/metadata/core/ajaxGetMetadata/*'
    - '/transition/**'
  filterChainUserMap:
    # 所有请求需要认证
    - '/**'
  filterChainonlineSessionMap:
    # 系统请求记录当前会话
    - '/main'
    - '/system/**'
    - '/monitor/**'
    - '/tool/**'

# 代码生成
gen: 
  # 作者
  author: censoft
  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
  packageName: com.censoft.project.module
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix: dev_