# 数据容器
datacapsule:
  download: 
    tools: censoft.exe
    document: censoft.txt
#单导
unipath:
#   单导文件位置
  filePath: d:/ww/client_temp_file/
jctable:
  dataSources: 外网
  convergeMeans: 数据上报，服务对接，数据交换，互联网采集
 

